### ISSUE TITLE
Simplify parties 

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#26]
Right now, we set up the parties like this. We assume the appellant is on the left side of the "v" and the appellee is on the right side.
```
\SetupPerson{RJS}{%
appellant,
firstparty,
name={Ryan Jusup Simon},
address={French Robertson Unit\\12071 FM 3522\\Abilene, TX 79601},
}

\appellee{The State of Texas}
```

Let's make the parties more flexible as far as side of the "v" and title. For example, sometimes the Appellee is on the left side of the v and called something different, like Plaintiff-Appellee.

for example, perhaps something like this:

\leftside{
Name={Ryan Simon}
Title={Defendant-Appellant}
}

\rightside{
Name={The State of Texas}
Title={Plaintiff-Appellee}
}

For "e" cases, the only party will be "leftside" and that's ok.

**Comment by frabyn** [comment]
Ok, wait, I'm rethinking how to do this.

For our purposes, there are at least three people in each appeal.

An Appellant, who may be on the left or the right side of the v, and may be called just appellant or something like appellant-defendant.

An Appellee, usually the government, is on the left or the right side and may be called Plaintiff-Appellee or something else.

So I think we should set this up to define people comprehensively, and to apply tags to the people to indicate two important things: title and position(s).

So
Name=Ryan Simon
Title=Defendant-Appellant
Position=leftv, appellant

Leftv would tell the document to put him on the cover page on the left side of the v with the title as specified. "Appellant' would tell the document to put him under that in the identity of parties and counsel.

We might also want to expand our defining people out to all the parties. So we would define the trial lawyers, and could also tag them as secondary lawyers to put on the brief cover.

Name=Joe Johnson
Title=Counsel for Appellant
Position=trialcounsel, oncover

**Comment by AndreyBPopov** [comment]
Yes, I agree! In fact, I implemented \SetupPerson structure assuming that we will use it in future for all peoples in document. However, since LaTeX implementation of  something like "Position=leftv, appellant"  may not be easy and reliable I would like propose slightly different scheme:
\SetupPerson{FB}{%
leadlawyer, **_**% this may be one of predefined keys, e.g. secondarylawer, appellant, appellee, judge, trialprosecutor or something else.... each of these keys automatically defines position ={} key to corresponding predefined value (e.g., position={Lead Counsel for Appellant} for lead lawyer), but if you want to change exactly position you can use position ={} key directly, so you can write  position ={Trial Counsel}. Also if you wish I can change the name of this key to title={}**_** 

firtsparty,  % _or secondparty, we will use firstparty key to indicate left side of v. and secondparty to indicated the right side of v., respectively. Why I would like to use firstparty/secondparty instead of leftv/rightv? It is because I believe that the end-user of well-designed style file NEVER should think aboutposition or formatting of elements, he must specify only corresponding values and style file must automatically format and put them in the right places_
name={Franklin Bynum},
%position={Lead Counsel for Appellant},%use this option to change position
barnumber={Texas Bar \#24069451},
address={2814 Hamilton Street\\Houston, Texas 77004},
phone={+1 713 343 8844},
email={franklin@bynumlaw.net}

It makes sense?

Yet another question: at first page you indicated as Lead Counsel for Appellant with address 2814 Hamilton Street\\Houston, Texas 77004, but at Identity of Parties and Counsel page I see:
Appellant’s Counsel Franklin Bynum
                                 Post Office Box 801
                                 Houston, Texas 77001
Is it right, or it should be
Lead Counsel for Appellant    Franklin Bynum
                                                2814 Hamilton Street\\Houston, Texas 77004
?

**Comment by frabyn** [comment]
Yes, that's perfect.

As for the addresses, the PO Box is a mistake. It should be Hamilton. Standardizing everything will help!

**Comment by AndreyBPopov** [comment]
Completed.
