### ISSUE TITLE
Shorten signature line

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#27]
Right now the signature line is significantly longer than the name "Franklin Bynum"

Please make it shorter, perhaps making it spaced exactly like the "Lead Counsel for Appellant" box on the cover page using makefrontmatter.

**Comment by AndreyBPopov** [comment]
I made that line longer since I thought that there must be a white space for hand-made people signature...
If not I can reduce it to the width of the name or position, but since position may be very long I propose to reduce it to the width of name+1cm.

Also please note that now you can produce the signature for each person defined in document, e.g., \MakeSignature{RJS} will produce signature for Ryan Jusup Simon...

**Comment by frabyn** [comment]
I think for the line, width of name + 1 cm is great. Let's also make the left indent for the signature blocks more to the right, making them even with the position of the "Lead Counsel" block on the cover page.

**Comment by AndreyBPopov** [comment]
Completed.
