### ISSUE TITLE
Add inmate identifier to address information

### ISSUE THREAD

**Issue by frabyn** [frabyn/simon-brief#32]
Part of a person'a address while they are in prison is their inmate identifier. This can be called a SPN, A TDC number, a register number, or any of countless other names.

All the numbers can be abbreviated to # followed by the number. The number always follows the name, either after a comma or on a new line

Either

`Franklin Bynum, # 02464341
`
or 

```
Franklin Bynum
# 0246241
```

In this case, we prefer to put the number following a comma.

So, for anyone defined in the persons-data.tex file, create a field for inmate number

Right now, addresses are defined for a person like this:

\SetupPerson{JS}{%
appellant,
firstparty,
name={John Smith, Jr.},
address={French Robertson Unit\\4304 Highway 202, Beeville, TX 78102},
number={123456}
}

And then whenever the postal address is printed, if a number is defined print it after the name.

DO not place the number everywhere the name appears in the document. For example, in the caption of the case the number must not appear. The number is only necessary to send mail, and should only be used when printing the address.

**Comment by AndreyBPopov** [comment]
I have used 'inmateid' for the field name instead of just 'number', i.e.
\SetupPerson{JS}{%
 appellant,
 firstparty,
 name={John Smith, Jr.},
 address={French Robertson Unit\4304 Highway 202, Beeville, TX 78102},
 inmateid={123456}
 }
Please use \PrintPersonNameWithAddress{shortcut} to print person name with his address, e.g. \PrintPersonNameWithAddress{RJS} or \PrintPersonNameWithAddress{FB}.

**Comment by AndreyBPopov** [comment]
Completed.
